# Generated by Django 4.0.2 on 2022-03-17 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название выполняемого проекта')),
                ('description', models.TextField(verbose_name='Что входит в проект')),
                ('link_repo', models.URLField(verbose_name='Ссылка на репозиторий проекта')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления проекта')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('customer_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uid заказчик проекта')),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления проекта')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userworkapp.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Не определена', max_length=64, verbose_name='Заметка')),
                ('description', models.TextField(default='Не определен', verbose_name='Текст заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус заметки')),
                ('is_close', models.BooleanField(default=False, verbose_name='закрыто')),
                ('scheduled_date', models.DateTimeField(verbose_name='Примерная дата завершения')),
                ('actual_date', models.DateTimeField(verbose_name='Фактическая дата завершения')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления проекта')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('customer_todo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uid заказчик заметки')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userworkapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления проекта')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userworkapp.todo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userworkapp.userworkingproject')),
            ],
        ),
    ]
