# Generated by Django 4.0.3 on 2022-03-27 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userworkapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executor',
            old_name='user',
            new_name='user_working_project',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='customer_todo',
        ),
        migrations.AlterField(
            model_name='project',
            name='customer_project',
            field=models.ForeignKey(default=1, on_delete=models.SET('n/a'), to=settings.AUTH_USER_MODEL, verbose_name='uid заказчика проекта'),
            preserve_default=False,
        ),
    ]
