# Generated by Django 4.0.3 on 2022-03-27 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('793b418f-aa4a-4028-94a1-366f93bf827a'), primary_key=True, serialize=False),
        ),
    ]
